// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: notifyd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1 // ждёт отправки (в т.ч. между ретраями)
	Status_STATUS_SENDING     Status = 2 // захвачено воркером прямо сейчас
	Status_STATUS_SENT        Status = 3 // терминальный
	Status_STATUS_CANCELLED   Status = 4 // терминальный
	Status_STATUS_DEAD        Status = 5 // терминальный: попытки исчерпаны
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_SENDING",
		3: "STATUS_SENT",
		4: "STATUS_CANCELLED",
		5: "STATUS_DEAD",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_SENDING":     2,
		"STATUS_SENT":        3,
		"STATUS_CANCELLED":   4,
		"STATUS_DEAD":        5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_notifyd_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_notifyd_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{0}
}

type CreateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Recipient string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // валидация: RFC 5322
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`         // 1..255
	Body      string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`           // 1..64KB
	// Types that are valid to be assigned to Schedule:
	//
	//	*CreateRequest_SendAt
	//	*CreateRequest_Delay
	Schedule       isCreateRequest_Schedule `protobuf_oneof:"schedule"`
	IdempotencyKey string                   `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // опционально
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_notifyd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateRequest) GetSchedule() isCreateRequest_Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *CreateRequest) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Schedule.(*CreateRequest_SendAt); ok {
			return x.SendAt
		}
	}
	return nil
}

func (x *CreateRequest) GetDelay() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Schedule.(*CreateRequest_Delay); ok {
			return x.Delay
		}
	}
	return nil
}

func (x *CreateRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type isCreateRequest_Schedule interface {
	isCreateRequest_Schedule()
}

type CreateRequest_SendAt struct {
	SendAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=send_at,json=sendAt,proto3,oneof"` // всегда UTC
}

type CreateRequest_Delay struct {
	Delay *durationpb.Duration `protobuf:"bytes,5,opt,name=delay,proto3,oneof"` // > 0
}

func (*CreateRequest_SendAt) isCreateRequest_Schedule() {}

func (*CreateRequest_Delay) isCreateRequest_Schedule() {}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SendAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_notifyd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateResponse) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_notifyd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=notify.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_notifyd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_notifyd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=notify.v1.Status" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_notifyd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ListRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Notification        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_notifyd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetItems() []*Notification {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SendAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=notify.v1.Status" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifyd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifyd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifyd_proto_rawDescGZIP(), []int{7}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

func (x *Notification) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Notification) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Notification) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_notifyd_proto protoreflect.FileDescriptor

const file_notifyd_proto_rawDesc = "" +
	"\n" +
	"\rnotifyd.proto\x12\tnotify.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf6\x01\n" +
	"\rCreateRequest\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x125\n" +
	"\asend_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x06sendAt\x121\n" +
	"\x05delay\x18\x05 \x01(\v2\x19.google.protobuf.DurationH\x00R\x05delay\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKeyB\n" +
	"\n" +
	"\bschedule\"U\n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\asend_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\"\x1f\n" +
	"\rCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x0eCancelResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.notify.v1.StatusR\x06status\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x01\n" +
	"\vListRequest\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.notify.v1.StatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"S\n" +
	"\fListResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.notify.v1.NotificationR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf1\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x123\n" +
	"\asend_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.notify.v1.StatusR\x06status\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\asent_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt*\x80\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SENDING\x10\x02\x12\x0f\n" +
	"\vSTATUS_SENT\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x04\x12\x0f\n" +
	"\vSTATUS_DEAD\x10\x052\x83\x02\n" +
	"\x13NotificationService\x12=\n" +
	"\x06Create\x12\x18.notify.v1.CreateRequest\x1a\x19.notify.v1.CreateResponse\x12=\n" +
	"\x06Cancel\x12\x18.notify.v1.CancelRequest\x1a\x19.notify.v1.CancelResponse\x125\n" +
	"\x03Get\x12\x15.notify.v1.GetRequest\x1a\x17.notify.v1.Notification\x127\n" +
	"\x04List\x12\x16.notify.v1.ListRequest\x1a\x17.notify.v1.ListResponseB(Z&github.com/kaynelza/NTF/pkg/notifyd/v1b\x06proto3"

var (
	file_notifyd_proto_rawDescOnce sync.Once
	file_notifyd_proto_rawDescData []byte
)

func file_notifyd_proto_rawDescGZIP() []byte {
	file_notifyd_proto_rawDescOnce.Do(func() {
		file_notifyd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifyd_proto_rawDesc), len(file_notifyd_proto_rawDesc)))
	})
	return file_notifyd_proto_rawDescData
}

var file_notifyd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notifyd_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notifyd_proto_goTypes = []any{
	(Status)(0),                   // 0: notify.v1.Status
	(*CreateRequest)(nil),         // 1: notify.v1.CreateRequest
	(*CreateResponse)(nil),        // 2: notify.v1.CreateResponse
	(*CancelRequest)(nil),         // 3: notify.v1.CancelRequest
	(*CancelResponse)(nil),        // 4: notify.v1.CancelResponse
	(*GetRequest)(nil),            // 5: notify.v1.GetRequest
	(*ListRequest)(nil),           // 6: notify.v1.ListRequest
	(*ListResponse)(nil),          // 7: notify.v1.ListResponse
	(*Notification)(nil),          // 8: notify.v1.Notification
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 10: google.protobuf.Duration
}
var file_notifyd_proto_depIdxs = []int32{
	9,  // 0: notify.v1.CreateRequest.send_at:type_name -> google.protobuf.Timestamp
	10, // 1: notify.v1.CreateRequest.delay:type_name -> google.protobuf.Duration
	9,  // 2: notify.v1.CreateResponse.send_at:type_name -> google.protobuf.Timestamp
	0,  // 3: notify.v1.CancelResponse.status:type_name -> notify.v1.Status
	0,  // 4: notify.v1.ListRequest.status:type_name -> notify.v1.Status
	8,  // 5: notify.v1.ListResponse.items:type_name -> notify.v1.Notification
	9,  // 6: notify.v1.Notification.send_at:type_name -> google.protobuf.Timestamp
	0,  // 7: notify.v1.Notification.status:type_name -> notify.v1.Status
	9,  // 8: notify.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	9,  // 9: notify.v1.Notification.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 10: notify.v1.NotificationService.Create:input_type -> notify.v1.CreateRequest
	3,  // 11: notify.v1.NotificationService.Cancel:input_type -> notify.v1.CancelRequest
	5,  // 12: notify.v1.NotificationService.Get:input_type -> notify.v1.GetRequest
	6,  // 13: notify.v1.NotificationService.List:input_type -> notify.v1.ListRequest
	2,  // 14: notify.v1.NotificationService.Create:output_type -> notify.v1.CreateResponse
	4,  // 15: notify.v1.NotificationService.Cancel:output_type -> notify.v1.CancelResponse
	8,  // 16: notify.v1.NotificationService.Get:output_type -> notify.v1.Notification
	7,  // 17: notify.v1.NotificationService.List:output_type -> notify.v1.ListResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_notifyd_proto_init() }
func file_notifyd_proto_init() {
	if File_notifyd_proto != nil {
		return
	}
	file_notifyd_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateRequest_SendAt)(nil),
		(*CreateRequest_Delay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifyd_proto_rawDesc), len(file_notifyd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifyd_proto_goTypes,
		DependencyIndexes: file_notifyd_proto_depIdxs,
		EnumInfos:         file_notifyd_proto_enumTypes,
		MessageInfos:      file_notifyd_proto_msgTypes,
	}.Build()
	File_notifyd_proto = out.File
	file_notifyd_proto_goTypes = nil
	file_notifyd_proto_depIdxs = nil
}
